server.port=8180
spring.application.name=GATEWAY-SERVICE
eureka.client.serviceUrl.defaultZone=http://tjpe295846.tjpe.gov.br:8761/eureka
eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
zuul.host.socket-timeout-millis=600000
zuul.host.connect-timeout-millis=600000
ribbon.ConnectTimeout=600000
ribbon.ReadTimeout=600000
zuul.sensitiveHeaders=