<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>jcr-storage-common</artifactId>
    <name>Pje JCR Storage Common</name>
    <description>Artefatos em comum entre JCR server e client</description>

    <parent>
        <groupId>br.jus.cnj.pje</groupId>
        <artifactId>jcr-storage</artifactId>
        <version>1.2.2</version>
    </parent>
    
    <dependencies>
        <!-- PJE Interfaces -->
        <dependency>
            <groupId>br.jus.cnj.pje</groupId>
            <artifactId>pje-interfaces</artifactId>
        </dependency>

        <!-- The JCR API -->
        <dependency>
            <groupId>javax.jcr</groupId>
            <artifactId>jcr</artifactId>
        </dependency>

        <!-- Jackrabbit content repository -->
        <dependency>
			<groupId>org.apache.jackrabbit</groupId>
			<artifactId>jackrabbit-core</artifactId>
		</dependency>

		<!-- Servlet API -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
		</dependency>
    </dependencies>
</project>
