# Repository URL (HTTP)
jcr.url=${jcr.client.url}

# Username and password
jcr.username=${jcr.client.username}
jcr.password=${jcr.client.password}

# Chunkize de 1Mb
jcr.chunkSize=${jcr.chunk-size}

# Maxium http connections
jcr.hostMaxConn=${jcr.client.max-connections}